CREATE SCHEMA "TEST4JAVA" AUTHORIZATION "TEST4JAVA";

CREATE TABLE "TEST4JAVA"."TEST_BLOB_ENTITY"
(
    "ID" VARCHAR2(36) NOT NULL,
    "BYTES" BLOB,
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "TEST", CLUSTERBTR) ;

COMMENT ON TABLE "TEST4JAVA"."TEST_BLOB_ENTITY" IS '测试读写文件数据';
COMMENT ON COLUMN "TEST4JAVA"."TEST_BLOB_ENTITY"."ID" IS '主键';
COMMENT ON COLUMN "TEST4JAVA"."TEST_BLOB_ENTITY"."BYTES" IS '文件数据';


CREATE TABLE "TEST4JAVA"."TEST_CLOB_ENTITY"
(
    "ID" VARCHAR2(36) NOT NULL,
    "TEXT" CLOB,
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "TEST", CLUSTERBTR) ;

COMMENT ON TABLE "TEST4JAVA"."TEST_CLOB_ENTITY" IS '测试读写长文本数据';
COMMENT ON COLUMN "TEST4JAVA"."TEST_CLOB_ENTITY"."ID" IS '主键';
COMMENT ON COLUMN "TEST4JAVA"."TEST_CLOB_ENTITY"."TEXT" IS '文本数据';


CREATE TABLE "TEST4JAVA"."TEST_GENERAL_ENTITY"
(
    "ID" VARCHAR2(36) NOT NULL,
    "CHAR" CHAR(20),
    "STRING" VARCHAR2(2000),
    "BYTE" TINYINT,
    "SHORT" SMALLINT,
    "INTEGER" INTEGER,
    "LONG" BIGINT,
    "FLOAT" FLOAT,
    "DOUBLE" FLOAT,
    "DECIMAL" DECIMAL(38,30),
    "BOOLEAN" NUMBER(1,0),
    "DATE" DATE,
    "TIME" INTERVAL DAY(2) TO SECOND(6),
    "DATETIME" TIMESTAMP(6),
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "TEST", CLUSTERBTR) ;

COMMENT ON TABLE "TEST4JAVA"."TEST_GENERAL_ENTITY" IS '测试读写常规数据';
COMMENT ON COLUMN "TEST4JAVA"."TEST_GENERAL_ENTITY"."ID" IS '主键';
COMMENT ON COLUMN "TEST4JAVA"."TEST_GENERAL_ENTITY"."CHAR" IS '字符';
COMMENT ON COLUMN "TEST4JAVA"."TEST_GENERAL_ENTITY"."STRING" IS '字符串';
COMMENT ON COLUMN "TEST4JAVA"."TEST_GENERAL_ENTITY"."BYTE" IS '8位整数';
COMMENT ON COLUMN "TEST4JAVA"."TEST_GENERAL_ENTITY"."SHORT" IS '16位整数';
COMMENT ON COLUMN "TEST4JAVA"."TEST_GENERAL_ENTITY"."INTEGER" IS '32位整数';
COMMENT ON COLUMN "TEST4JAVA"."TEST_GENERAL_ENTITY"."LONG" IS '64位整数';
COMMENT ON COLUMN "TEST4JAVA"."TEST_GENERAL_ENTITY"."FLOAT" IS '单精度浮点数';
COMMENT ON COLUMN "TEST4JAVA"."TEST_GENERAL_ENTITY"."DOUBLE" IS '双精度浮点数';
COMMENT ON COLUMN "TEST4JAVA"."TEST_GENERAL_ENTITY"."DECIMAL" IS '高精度浮点数';
COMMENT ON COLUMN "TEST4JAVA"."TEST_GENERAL_ENTITY"."BOOLEAN" IS '布尔';
COMMENT ON COLUMN "TEST4JAVA"."TEST_GENERAL_ENTITY"."DATE" IS '日期';
COMMENT ON COLUMN "TEST4JAVA"."TEST_GENERAL_ENTITY"."TIME" IS '时间';
COMMENT ON COLUMN "TEST4JAVA"."TEST_GENERAL_ENTITY"."DATETIME" IS '日期时间';


CREATE TABLE "TEST4JAVA"."TEST_IDENTITY_ENTITY"
(
    "ID" BIGINT IDENTITY(1, 1) NOT NULL,
    "NO" VARCHAR2(36),
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "TEST", CLUSTERBTR) ;

COMMENT ON TABLE "TEST4JAVA"."TEST_IDENTITY_ENTITY" IS '测试自增主键';
COMMENT ON COLUMN "TEST4JAVA"."TEST_IDENTITY_ENTITY"."ID" IS '自增主键';
COMMENT ON COLUMN "TEST4JAVA"."TEST_IDENTITY_ENTITY"."NO" IS '编号';


