/*
 Navicat Premium Data Transfer

 Source Server         : 192.168.1.44 Oracle 19c PDB (test4java)
 Source Server Type    : Oracle
 Source Server Version : 190000
 Source Host           : 192.168.1.44:1521
 Source Schema         : TEST4JAVA

 Target Server Type    : Oracle
 Target Server Version : 190000
 File Encoding         : 65001

 Date: 04/04/2023 17:57:31
*/


-- ----------------------------
-- Table structure for TEST_BLOB_ENTITY
-- ----------------------------
DROP TABLE "TEST4JAVA"."TEST_BLOB_ENTITY";
CREATE TABLE "TEST4JAVA"."TEST_BLOB_ENTITY" (
  "ID" VARCHAR2(36 BYTE) VISIBLE NOT NULL,
  "BYTES" LONG RAW VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "TEST4JAVA"."TEST_BLOB_ENTITY"."ID" IS '主键';
COMMENT ON COLUMN "TEST4JAVA"."TEST_BLOB_ENTITY"."BYTES" IS '文件数据';
COMMENT ON TABLE "TEST4JAVA"."TEST_BLOB_ENTITY" IS '测试读写文件数据';

-- ----------------------------
-- Table structure for TEST_CLOB_ENTITY
-- ----------------------------
DROP TABLE "TEST4JAVA"."TEST_CLOB_ENTITY";
CREATE TABLE "TEST4JAVA"."TEST_CLOB_ENTITY" (
  "ID" VARCHAR2(36 BYTE) VISIBLE NOT NULL,
  "TEXT" LONG VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "TEST4JAVA"."TEST_CLOB_ENTITY"."ID" IS '主键';
COMMENT ON COLUMN "TEST4JAVA"."TEST_CLOB_ENTITY"."TEXT" IS '文本数据';
COMMENT ON TABLE "TEST4JAVA"."TEST_CLOB_ENTITY" IS '测试读写长文本数据';

-- ----------------------------
-- Table structure for TEST_GENERAL_ENTITY
-- ----------------------------
DROP TABLE "TEST4JAVA"."TEST_GENERAL_ENTITY";
CREATE TABLE "TEST4JAVA"."TEST_GENERAL_ENTITY" (
  "ID" NVARCHAR2(36) VISIBLE NOT NULL,
  "CHAR" NCHAR(1) VISIBLE,
  "STRING" NVARCHAR2(200) VISIBLE,
  "BYTE" NUMBER(3,0) VISIBLE,
  "SHORT" NUMBER(5,0) VISIBLE,
  "INTEGER" NUMBER(10,0) VISIBLE,
  "LONG" NUMBER(19,0) VISIBLE,
  "FLOAT" FLOAT(63) VISIBLE,
  "DOUBLE" FLOAT(126) VISIBLE,
  "DECIMAL" NUMBER(38,30) VISIBLE,
  "BOOLEAN" NUMBER(1,0) VISIBLE,
  "DATE" DATE VISIBLE,
  "TIME" DATE VISIBLE,
  "DATETIME" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "TEST4JAVA"."TEST_GENERAL_ENTITY"."ID" IS '主键';
COMMENT ON COLUMN "TEST4JAVA"."TEST_GENERAL_ENTITY"."CHAR" IS '字符';
COMMENT ON COLUMN "TEST4JAVA"."TEST_GENERAL_ENTITY"."STRING" IS '字符串';
COMMENT ON COLUMN "TEST4JAVA"."TEST_GENERAL_ENTITY"."BYTE" IS '8位整数';
COMMENT ON COLUMN "TEST4JAVA"."TEST_GENERAL_ENTITY"."SHORT" IS '16位整数';
COMMENT ON COLUMN "TEST4JAVA"."TEST_GENERAL_ENTITY"."INTEGER" IS '32位整数';
COMMENT ON COLUMN "TEST4JAVA"."TEST_GENERAL_ENTITY"."LONG" IS '64位整数';
COMMENT ON COLUMN "TEST4JAVA"."TEST_GENERAL_ENTITY"."FLOAT" IS '单精度浮点数';
COMMENT ON COLUMN "TEST4JAVA"."TEST_GENERAL_ENTITY"."DOUBLE" IS '双精度浮点数';
COMMENT ON COLUMN "TEST4JAVA"."TEST_GENERAL_ENTITY"."DECIMAL" IS '高精度浮点数';
COMMENT ON COLUMN "TEST4JAVA"."TEST_GENERAL_ENTITY"."BOOLEAN" IS '布尔';
COMMENT ON COLUMN "TEST4JAVA"."TEST_GENERAL_ENTITY"."DATE" IS '日期';
COMMENT ON COLUMN "TEST4JAVA"."TEST_GENERAL_ENTITY"."TIME" IS '时间';
COMMENT ON COLUMN "TEST4JAVA"."TEST_GENERAL_ENTITY"."DATETIME" IS '日期时间';
COMMENT ON TABLE "TEST4JAVA"."TEST_GENERAL_ENTITY" IS '测试读写常规数据';

-- ----------------------------
-- Table structure for TEST_IDENTITY_ENTITY
-- ----------------------------
DROP TABLE "TEST4JAVA"."TEST_IDENTITY_ENTITY";
CREATE TABLE "TEST4JAVA"."TEST_IDENTITY_ENTITY" (
  "ID" NUMBER(19,0) VISIBLE DEFAULT "TEST4JAVA"."ISEQ$$_73261".nextval NOT NULL,
  "NO" VARCHAR2(36 BYTE) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "TEST4JAVA"."TEST_IDENTITY_ENTITY"."ID" IS '自增主键';
COMMENT ON COLUMN "TEST4JAVA"."TEST_IDENTITY_ENTITY"."NO" IS '编号';
COMMENT ON TABLE "TEST4JAVA"."TEST_IDENTITY_ENTITY" IS '测试自增主键';

-- ----------------------------
-- Function structure for NAIVE_SQL_LONG_TO_CHAR_DEFAULT
-- ----------------------------
CREATE OR REPLACE
FUNCTION "TEST4JAVA"."NAIVE_SQL_LONG_TO_CHAR_DEFAULT" AS
BEGIN
  DBMS_OUTPUT.ENABLE(BUFFER_SIZE => NULL);
  SQL_CUR := 'SELECT T.DATA_DEFAULT FROM USER_TAB_COLUMNS T WHERE T.TABLE_NAME = '''||TABLE_NAME||''' AND T.COLUMN_NAME='''||COLUMN||'''';
  DBMS_OUTPUT.PUT_LINE(SQL_CUR);
  EXECUTE IMMEDIATE SQL_CUR
    INTO TEXT_C1;
  TEXT_C1 := SUBSTR(TEXT_C1, 1, 4000);
  RETURN TEXT_C1;
END;
/

-- ----------------------------
-- Function structure for NAIVE_SQL_LONG_TO_VARCHAR
-- ----------------------------
CREATE OR REPLACE
FUNCTION "TEST4JAVA"."NAIVE_SQL_LONG_TO_VARCHAR" AS
BEGIN
   SELECT COLUMN_EXPRESSION
     INTO l_COLUMN_EXPRESSION
     FROM user_ind_expressions  
    WHERE     index_name = p_index_name
          AND table_name = p_table_name
          AND COLUMN_POSITION = p_COLUMN_POSITION;
  
   RETURN SUBSTR (l_COLUMN_EXPRESSION, 1, 4000);
END;
/

-- ----------------------------
-- Sequence structure for ISEQ$$_73258
-- ----------------------------
DROP SEQUENCE "TEST4JAVA"."ISEQ$$_73258";
CREATE SEQUENCE "TEST4JAVA"."ISEQ$$_73258" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for ISEQ$$_73261
-- ----------------------------
DROP SEQUENCE "TEST4JAVA"."ISEQ$$_73261";
CREATE SEQUENCE "TEST4JAVA"."ISEQ$$_73261" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Primary Key structure for table TEST_BLOB_ENTITY
-- ----------------------------
ALTER TABLE "TEST4JAVA"."TEST_BLOB_ENTITY" ADD CONSTRAINT "SYS_C007675" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table TEST_BLOB_ENTITY
-- ----------------------------
ALTER TABLE "TEST4JAVA"."TEST_BLOB_ENTITY" ADD CONSTRAINT "SYS_C007674" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table TEST_CLOB_ENTITY
-- ----------------------------
ALTER TABLE "TEST4JAVA"."TEST_CLOB_ENTITY" ADD CONSTRAINT "SYS_C007679" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table TEST_CLOB_ENTITY
-- ----------------------------
ALTER TABLE "TEST4JAVA"."TEST_CLOB_ENTITY" ADD CONSTRAINT "SYS_C007678" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table TEST_GENERAL_ENTITY
-- ----------------------------
ALTER TABLE "TEST4JAVA"."TEST_GENERAL_ENTITY" ADD CONSTRAINT "SYS_C007605" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table TEST_GENERAL_ENTITY
-- ----------------------------
ALTER TABLE "TEST4JAVA"."TEST_GENERAL_ENTITY" ADD CONSTRAINT "SYS_C007603" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TEST4JAVA"."TEST_GENERAL_ENTITY" ADD CONSTRAINT "SYS_C007660" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table TEST_IDENTITY_ENTITY
-- ----------------------------
ALTER TABLE "TEST4JAVA"."TEST_IDENTITY_ENTITY" ADD CONSTRAINT "SYS_C007670" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table TEST_IDENTITY_ENTITY
-- ----------------------------
ALTER TABLE "TEST4JAVA"."TEST_IDENTITY_ENTITY" ADD CONSTRAINT "SYS_C007669" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
